import type { PatternBlueprintKind } from '../composition/blueprints'

export const primitiveCatalogGroups = [
  {
    title: 'Controls',
    items: [
      'Button',
      'IconButton',
      'ControlRow',
      'ChoiceRow',
      'SegmentedControl',
    ],
  },
  {
    title: 'Forms',
    items: [
      'Field',
      'FieldGroup',
      'InputFrame',
      'TextInput',
      'RangeInput',
      'CheckboxInput',
      'CheckboxRow',
      'MeterBar',
    ],
  },
  {
    title: 'Rows / Lists',
    items: [
      'MetaRow',
      'KeyValueRow',
      'ValueList',
      'DetailRow',
      'RecordList',
      'CodeList',
      'DeltaRow',
      'DeltaList',
      'CheckRow',
      'StatusList',
      'ItemRow',
      'ItemList',
      'DataTable',
      'MeterRow',
      'MeterList',
    ],
  },
  {
    title: 'Atoms',
    items: [
      'Badge',
      'Swatch',
      'SkeletonLine',
      'SkeletonStack',
      'Description',
      'InlineCode',
      'CodeLine',
      'DeltaPair',
      'StateBadge',
      'EmptyState',
    ],
  },
  {
    title: 'Sections',
    items: [
      'Section',
      'ListSection',
      'TableSection',
      'GridSection',
      'FormSection',
      'PlaceholderSection',
      'TreeSection',
    ],
  },
  {
    title: 'Formulas',
    items: [
      'SectionBlock',
      'SectionStackBlock',
      'SectionPairBlock',
      'SectionTrioBlock',
      'SectionGridBlock',
      'CodeSectionBlock',
      'DeltaSectionBlock',
      'ItemSectionBlock',
      'MetricSectionBlock',
      'MeterSectionBlock',
      'RecordSectionBlock',
      'StatusSectionBlock',
      'ValueSectionBlock',
      'SurfaceBlock',
      'TableBlock',
      'GridBlock',
      'TreeBlock',
      'TextBlock',
      'MetaBlock',
    ],
  },
  {
    title: 'Layout',
    items: [
      'Cluster',
      'RowStack',
      'Prose',
      'Titlebar',
      'SectionStack',
      'SectionGrid',
      'PageLayout',
      'PageFrame',
      'AreaGrid',
      'Area',
      'NavStack',
      'TabRow',
      'SplitView',
      'Pane',
      'CollectionGrid',
      'SectionGroup',
      'IndentedStack',
      'IndentedItem',
      'TextStack',
    ],
  },
  {
    title: 'Compositions',
    items: ['Navigation', 'NavigationSection', 'StateColumn', 'TitledGrid'],
  },
  {
    title: 'Shell',
    items: [
      'ShellFrame',
      'ShellRail',
      'ShellMain',
      'ShellTopbar',
      'ShellSurface',
      'ShellInspector',
      'Breadcrumb',
      'ScrollStack',
      'NavGroup',
      'FloatingPanel',
      'FloatingPanelBody',
    ],
  },
] as const

export const apgBlueprintKinds: Record<string, PatternBlueprintKind> = {
  ApgAccordion: 'disclosure',
  ApgAlert: 'message',
  ApgAlertDialog: 'dialog',
  ApgBreadcrumb: 'navigation',
  ApgButton: 'command',
  ApgCarousel: 'layout',
  ApgCheckbox: 'field',
  ApgCombobox: 'field',
  ApgDialog: 'dialog',
  ApgDisclosure: 'disclosure',
  ApgFeed: 'feed',
  ApgGrid: 'data',
  ApgLandmarks: 'layout',
  ApgLink: 'command',
  ApgListbox: 'field',
  ApgMenuButton: 'disclosure',
  ApgMenubar: 'navigation',
  ApgMeter: 'range',
  ApgRadioGroup: 'field',
  ApgSlider: 'range',
  ApgSpinbutton: 'field',
  ApgSwitch: 'command',
  ApgTable: 'data',
  ApgTabs: 'navigation',
  ApgToolbar: 'navigation',
  ApgTooltip: 'message',
  ApgTreegrid: 'data',
  ApgTreeview: 'tree',
  ApgWindowSplitter: 'layout',
}
