import type { ReactNode } from 'react'
import {
  ApgAccordion,
  ApgAlert,
  ApgAlertDialog,
  ApgBreadcrumb,
  ApgButton,
  ApgCarousel,
  ApgCheckbox,
  ApgCombobox,
  ApgDialog,
  ApgDisclosure,
  ApgFeed,
  ApgGrid,
  ApgLandmarks,
  ApgLink,
  ApgListbox,
  ApgMenuButton,
  ApgMenubar,
  ApgMeter,
  ApgRadioGroup,
  ApgSlider,
  ApgSpinbutton,
  ApgSwitch,
  ApgTable,
  ApgTabs,
  ApgToolbar,
  ApgTooltip,
  ApgTreegrid,
  ApgTreeview,
  ApgWindowSplitter,
} from './ApgComponents'

export const apgComponentPreviews: Record<string, ReactNode> = {
  ApgAccordion: <ApgAccordion />,
  ApgAlert: <ApgAlert />,
  ApgAlertDialog: <ApgAlertDialog />,
  ApgBreadcrumb: <ApgBreadcrumb />,
  ApgButton: <ApgButton />,
  ApgCarousel: <ApgCarousel />,
  ApgCheckbox: <ApgCheckbox />,
  ApgCombobox: <ApgCombobox />,
  ApgDialog: <ApgDialog />,
  ApgDisclosure: <ApgDisclosure />,
  ApgFeed: <ApgFeed />,
  ApgGrid: <ApgGrid />,
  ApgLandmarks: <ApgLandmarks />,
  ApgLink: <ApgLink />,
  ApgListbox: <ApgListbox />,
  ApgMenuButton: <ApgMenuButton />,
  ApgMenubar: <ApgMenubar />,
  ApgMeter: <ApgMeter />,
  ApgRadioGroup: <ApgRadioGroup />,
  ApgSlider: <ApgSlider />,
  ApgSpinbutton: <ApgSpinbutton />,
  ApgSwitch: <ApgSwitch />,
  ApgTable: <ApgTable />,
  ApgTabs: <ApgTabs />,
  ApgToolbar: <ApgToolbar />,
  ApgTooltip: <ApgTooltip />,
  ApgTreegrid: <ApgTreegrid />,
  ApgTreeview: <ApgTreeview />,
  ApgWindowSplitter: <ApgWindowSplitter />,
}
